package pr.pkg21_malchev_projectwork1;


import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.io.FileWriter;
import java.io.IOException;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.BorderFactory;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    private boolean isClientConnnected = false;
    
    private Client client;
    private int firstQuizzRightAnswers = 0;
    private int secondQuizzRightAnswers = 0;
    
    private User myUser;
    
    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        chatStartingWindow.setBounds(0, 0, 414, 500);
        chatStartingWindow.setLocationRelativeTo(null);
        
        chatWindow.setBounds(0, 0, 584, 470);
        chatWindow.setLocationRelativeTo(null);
        
        serverIsWorkingWindow.setBounds(0,0,420,400);
        serverIsWorkingWindow.setLocationRelativeTo(null);
        
        registrationWindow.setBounds(0, 0, 400, 300);
        registrationWindow.setLocationRelativeTo(null);
        
        activityStartingMenu.setBounds(0, 0, 400, 250);
        activityStartingMenu.setLocationRelativeTo(null);
        
        quizz1Maksimovs.setBounds(0,0,498,730);
        quizz1Maksimovs.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationWindow = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        reg_firstName_textField = new javax.swing.JTextField();
        reg_secondName_textField = new javax.swing.JTextField();
        reg_username_textField = new javax.swing.JTextField();
        reg_password_textField = new javax.swing.JTextField();
        reg_passwordOneMore_textField = new javax.swing.JTextField();
        saveRegistrationDataButton = new javax.swing.JButton();
        reg_info_label = new javax.swing.JLabel();
        chatWindow = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        userMessageField = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextPane();
        chatStartingWindow = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        BeHostButton = new javax.swing.JButton();
        BeClientButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        firstQuizz_RightAnswersNumber = new javax.swing.JLabel();
        serverIsWorkingWindow = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serverOutputArea = new javax.swing.JTextArea();
        testStartingWindow = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        activityStartingMenu = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        quizz1Maksimovs = new javax.swing.JDialog();
        questionsPanel = new javax.swing.JPanel();
        closeFirstQuizzButton = new javax.swing.JButton();
        FirstQuestion = new javax.swing.JPanel();
        quizz1_firstQuestion_Label = new javax.swing.JLabel();
        quizz1_firstQuestion_RadioButton1 = new javax.swing.JRadioButton();
        quizz1_firstQuestion_RadioButton2 = new javax.swing.JRadioButton();
        quizz1_firstQuestion_RadioButton3 = new javax.swing.JRadioButton();
        SecondQuestion = new javax.swing.JPanel();
        quizz1_secondQuestion_Label = new javax.swing.JLabel();
        quizz1_secondQuestion_TextField = new javax.swing.JTextField();
        ThirdQuestion = new javax.swing.JPanel();
        quizz1_thirdQuestion_Label = new javax.swing.JLabel();
        quizz1_thirdQuestion_ScrollPane = new javax.swing.JScrollPane();
        quizz2_thirdQuestion_List = new javax.swing.JList<>();
        FourthQuestion = new javax.swing.JPanel();
        quizz1_fourthQuestion_Label = new javax.swing.JLabel();
        quizz1_fourthQuestion_CheckBox1 = new javax.swing.JCheckBox();
        quizz1_fourthQuestion_CheckBox2 = new javax.swing.JCheckBox();
        quizz1_fourthQuestion_CheckBox3 = new javax.swing.JCheckBox();
        quizz1_fourthQuestion_CheckBox4 = new javax.swing.JCheckBox();
        FifthQuestion = new javax.swing.JPanel();
        quizz1_fifthQuestion_Label = new javax.swing.JLabel();
        quizz1_fifthQuestion_ComboBoxl = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        main_username = new javax.swing.JTextField();
        main_password = new javax.swing.JTextField();
        enterProgrammButton = new javax.swing.JButton();
        openRegistrationMenuButton = new javax.swing.JButton();
        main_info_label = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel3.setText("Vards:");

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel4.setText("Uzvards:");

        jLabel5.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel5.setText("Lietotajvards:");

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel6.setText("Parole:");

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel7.setText("Parole (atkartoti):");

        saveRegistrationDataButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveRegistrationDataButton.setText("Reģistrēties");
        saveRegistrationDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRegistrationDataButtonActionPerformed(evt);
            }
        });

        reg_info_label.setForeground(new java.awt.Color(255, 0, 0));
        reg_info_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reg_info_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reg_firstName_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(reg_secondName_textField)
                            .addComponent(reg_username_textField)
                            .addComponent(reg_password_textField)
                            .addComponent(reg_passwordOneMore_textField))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(saveRegistrationDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reg_firstName_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reg_secondName_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(reg_username_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(reg_password_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(reg_passwordOneMore_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reg_info_label, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveRegistrationDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout registrationWindowLayout = new javax.swing.GroupLayout(registrationWindow.getContentPane());
        registrationWindow.getContentPane().setLayout(registrationWindowLayout);
        registrationWindowLayout.setHorizontalGroup(
            registrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        registrationWindowLayout.setVerticalGroup(
            registrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chatWindow.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                chatWindowWindowClosing(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Your name"));

        userMessageField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userMessageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMessageFieldActionPerformed(evt);
            }
        });

        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        chatArea.setEditable(false);
        jScrollPane1.setViewportView(chatArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(userMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userMessageField)
                    .addComponent(SendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout chatWindowLayout = new javax.swing.GroupLayout(chatWindow.getContentPane());
        chatWindow.getContentPane().setLayout(chatWindowLayout);
        chatWindowLayout.setHorizontalGroup(
            chatWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        chatWindowLayout.setVerticalGroup(
            chatWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        chatStartingWindow.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                chatStartingWindowWindowClosing(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BeHostButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BeHostButton.setText("Start server");
        BeHostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeHostButtonActionPerformed(evt);
            }
        });

        BeClientButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BeClientButton.setText("Connect to server");
        BeClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeClientButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 100)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Chat");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Start Test");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        firstQuizz_RightAnswersNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstQuizz_RightAnswersNumber.setText("Right answers: unknown");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstQuizz_RightAnswersNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BeHostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BeClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeHostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstQuizz_RightAnswersNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout chatStartingWindowLayout = new javax.swing.GroupLayout(chatStartingWindow.getContentPane());
        chatStartingWindow.getContentPane().setLayout(chatStartingWindowLayout);
        chatStartingWindowLayout.setHorizontalGroup(
            chatStartingWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatStartingWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chatStartingWindowLayout.setVerticalGroup(
            chatStartingWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatStartingWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        serverIsWorkingWindow.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                serverIsWorkingWindowWindowClosing(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Server"));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SERVER IS WORKING!");

        serverOutputArea.setEditable(false);
        serverOutputArea.setColumns(20);
        serverOutputArea.setRows(5);
        jScrollPane2.setViewportView(serverOutputArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout serverIsWorkingWindowLayout = new javax.swing.GroupLayout(serverIsWorkingWindow.getContentPane());
        serverIsWorkingWindow.getContentPane().setLayout(serverIsWorkingWindowLayout);
        serverIsWorkingWindowLayout.setHorizontalGroup(
            serverIsWorkingWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverIsWorkingWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        serverIsWorkingWindowLayout.setVerticalGroup(
            serverIsWorkingWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverIsWorkingWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tests Nosaukums");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Start");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout testStartingWindowLayout = new javax.swing.GroupLayout(testStartingWindow.getContentPane());
        testStartingWindow.getContentPane().setLayout(testStartingWindowLayout);
        testStartingWindowLayout.setHorizontalGroup(
            testStartingWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testStartingWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        testStartingWindowLayout.setVerticalGroup(
            testStartingWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testStartingWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Activities");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Paper, rock, scissors");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout activityStartingMenuLayout = new javax.swing.GroupLayout(activityStartingMenu.getContentPane());
        activityStartingMenu.getContentPane().setLayout(activityStartingMenuLayout);
        activityStartingMenuLayout.setHorizontalGroup(
            activityStartingMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityStartingMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        activityStartingMenuLayout.setVerticalGroup(
            activityStartingMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityStartingMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        quizz1Maksimovs.setTitle("First Quizz");
        quizz1Maksimovs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                quizz1MaksimovsWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                quizz1MaksimovsWindowDeactivated(evt);
            }
        });

        questionsPanel.setBackground(new java.awt.Color(35, 39, 42));
        questionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Quizz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(152, 101, 242))); // NOI18N
        questionsPanel.setToolTipText("");

        closeFirstQuizzButton.setBackground(new java.awt.Color(152, 101, 242));
        closeFirstQuizzButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        closeFirstQuizzButton.setForeground(new java.awt.Color(255, 255, 255));
        closeFirstQuizzButton.setText("Pabeigt");
        closeFirstQuizzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFirstQuizzButtonActionPerformed(evt);
            }
        });

        FirstQuestion.setBackground(new java.awt.Color(44, 47, 51));
        FirstQuestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quizz1_firstQuestion_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quizz1_firstQuestion_Label.setForeground(new java.awt.Color(152, 101, 242));
        quizz1_firstQuestion_Label.setText("Kāda stunda māca saskaitīšanu un atņemšanu?");

        quizz1_firstQuestion_RadioButton1.setBackground(new java.awt.Color(44, 47, 51));
        quizz1_firstQuestion_RadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        quizz1_firstQuestion_RadioButton1.setText("Matematika");

        quizz1_firstQuestion_RadioButton2.setBackground(new java.awt.Color(44, 47, 51));
        quizz1_firstQuestion_RadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        quizz1_firstQuestion_RadioButton2.setText("Biologija");

        quizz1_firstQuestion_RadioButton3.setBackground(new java.awt.Color(44, 47, 51));
        quizz1_firstQuestion_RadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        quizz1_firstQuestion_RadioButton3.setText("Ķīmija");

        javax.swing.GroupLayout FirstQuestionLayout = new javax.swing.GroupLayout(FirstQuestion);
        FirstQuestion.setLayout(FirstQuestionLayout);
        FirstQuestionLayout.setHorizontalGroup(
            FirstQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FirstQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quizz1_firstQuestion_RadioButton3)
                    .addComponent(quizz1_firstQuestion_RadioButton1)
                    .addComponent(quizz1_firstQuestion_Label)
                    .addComponent(quizz1_firstQuestion_RadioButton2))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        FirstQuestionLayout.setVerticalGroup(
            FirstQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizz1_firstQuestion_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizz1_firstQuestion_RadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizz1_firstQuestion_RadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizz1_firstQuestion_RadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SecondQuestion.setBackground(new java.awt.Color(44, 47, 51));
        SecondQuestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quizz1_secondQuestion_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quizz1_secondQuestion_Label.setForeground(new java.awt.Color(152, 101, 242));
        quizz1_secondQuestion_Label.setText("Kurā stundā veic fiziskos vingrinājumus?");

        quizz1_secondQuestion_TextField.setToolTipText("");

        javax.swing.GroupLayout SecondQuestionLayout = new javax.swing.GroupLayout(SecondQuestion);
        SecondQuestion.setLayout(SecondQuestionLayout);
        SecondQuestionLayout.setHorizontalGroup(
            SecondQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SecondQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecondQuestionLayout.createSequentialGroup()
                        .addComponent(quizz1_secondQuestion_Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(quizz1_secondQuestion_TextField))
                .addContainerGap())
        );
        SecondQuestionLayout.setVerticalGroup(
            SecondQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizz1_secondQuestion_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizz1_secondQuestion_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ThirdQuestion.setBackground(new java.awt.Color(44, 47, 51));
        ThirdQuestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quizz1_thirdQuestion_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quizz1_thirdQuestion_Label.setForeground(new java.awt.Color(152, 101, 242));
        quizz1_thirdQuestion_Label.setText("Cik klases ir vidusskolā?");

        quizz2_thirdQuestion_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "4 klases", "12 klases", "5 klases", "9 klases" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        quizz2_thirdQuestion_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        quizz1_thirdQuestion_ScrollPane.setViewportView(quizz2_thirdQuestion_List);

        javax.swing.GroupLayout ThirdQuestionLayout = new javax.swing.GroupLayout(ThirdQuestion);
        ThirdQuestion.setLayout(ThirdQuestionLayout);
        ThirdQuestionLayout.setHorizontalGroup(
            ThirdQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThirdQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThirdQuestionLayout.createSequentialGroup()
                        .addComponent(quizz1_thirdQuestion_Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(quizz1_thirdQuestion_ScrollPane))
                .addContainerGap())
        );
        ThirdQuestionLayout.setVerticalGroup(
            ThirdQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizz1_thirdQuestion_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizz1_thirdQuestion_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        FourthQuestion.setBackground(new java.awt.Color(44, 47, 51));
        FourthQuestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quizz1_fourthQuestion_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quizz1_fourthQuestion_Label.setForeground(new java.awt.Color(152, 101, 242));
        quizz1_fourthQuestion_Label.setText("Ko vecāki dažreiz dara savu skolēnu vietā?");

        quizz1_fourthQuestion_CheckBox1.setBackground(new java.awt.Color(44, 47, 51));
        quizz1_fourthQuestion_CheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        quizz1_fourthQuestion_CheckBox1.setText("Atrisiniet mājasdarbu");

        quizz1_fourthQuestion_CheckBox2.setBackground(new java.awt.Color(44, 47, 51));
        quizz1_fourthQuestion_CheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        quizz1_fourthQuestion_CheckBox2.setText("Savāc mugursomu");

        quizz1_fourthQuestion_CheckBox3.setBackground(new java.awt.Color(44, 47, 51));
        quizz1_fourthQuestion_CheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        quizz1_fourthQuestion_CheckBox3.setText("Viņi iet uz nodarbībām");

        quizz1_fourthQuestion_CheckBox4.setBackground(new java.awt.Color(44, 47, 51));
        quizz1_fourthQuestion_CheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        quizz1_fourthQuestion_CheckBox4.setText("Atrisiniet eksāmenu");

        javax.swing.GroupLayout FourthQuestionLayout = new javax.swing.GroupLayout(FourthQuestion);
        FourthQuestion.setLayout(FourthQuestionLayout);
        FourthQuestionLayout.setHorizontalGroup(
            FourthQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourthQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FourthQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quizz1_fourthQuestion_Label)
                    .addComponent(quizz1_fourthQuestion_CheckBox3)
                    .addComponent(quizz1_fourthQuestion_CheckBox2)
                    .addComponent(quizz1_fourthQuestion_CheckBox4)
                    .addComponent(quizz1_fourthQuestion_CheckBox1))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        FourthQuestionLayout.setVerticalGroup(
            FourthQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourthQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizz1_fourthQuestion_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quizz1_fourthQuestion_CheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quizz1_fourthQuestion_CheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quizz1_fourthQuestion_CheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quizz1_fourthQuestion_CheckBox4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FifthQuestion.setBackground(new java.awt.Color(44, 47, 51));
        FifthQuestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quizz1_fifthQuestion_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quizz1_fifthQuestion_Label.setForeground(new java.awt.Color(152, 101, 242));
        quizz1_fifthQuestion_Label.setText("Kā sauc to personu, kas ir atbildīga par skolas vadīšanu?");

        quizz1_fifthQuestion_ComboBoxl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skolotājs", "Tīrīšanas sieviete", "Direktors", "Direktora vietnieks" }));

        javax.swing.GroupLayout FifthQuestionLayout = new javax.swing.GroupLayout(FifthQuestion);
        FifthQuestion.setLayout(FifthQuestionLayout);
        FifthQuestionLayout.setHorizontalGroup(
            FifthQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FifthQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FifthQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FifthQuestionLayout.createSequentialGroup()
                        .addComponent(quizz1_fifthQuestion_Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(quizz1_fifthQuestion_ComboBoxl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        FifthQuestionLayout.setVerticalGroup(
            FifthQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FifthQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizz1_fifthQuestion_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quizz1_fifthQuestion_ComboBoxl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout questionsPanelLayout = new javax.swing.GroupLayout(questionsPanel);
        questionsPanel.setLayout(questionsPanelLayout);
        questionsPanelLayout.setHorizontalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeFirstQuizzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FirstQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ThirdQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FourthQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FifthQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SecondQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        questionsPanelLayout.setVerticalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SecondQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ThirdQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FourthQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FifthQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeFirstQuizzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout quizz1MaksimovsLayout = new javax.swing.GroupLayout(quizz1Maksimovs.getContentPane());
        quizz1Maksimovs.getContentPane().setLayout(quizz1MaksimovsLayout);
        quizz1MaksimovsLayout.setHorizontalGroup(
            quizz1MaksimovsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizz1MaksimovsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        quizz1MaksimovsLayout.setVerticalGroup(
            quizz1MaksimovsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizz1MaksimovsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel1.setText("Lietotajvards:");

        jLabel2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel2.setText("Parole:");

        enterProgrammButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enterProgrammButton.setText("Ielogoties");
        enterProgrammButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterProgrammButtonActionPerformed(evt);
            }
        });

        openRegistrationMenuButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        openRegistrationMenuButton.setText("Reģistrēties");
        openRegistrationMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRegistrationMenuButtonActionPerformed(evt);
            }
        });

        main_info_label.setForeground(new java.awt.Color(255, 51, 51));
        main_info_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(main_info_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(main_username)
                            .addComponent(main_password)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(enterProgrammButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(openRegistrationMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(main_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(main_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_info_label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterProgrammButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openRegistrationMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openRegistrationMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRegistrationMenuButtonActionPerformed
        registrationWindow.setVisible(true);
    }//GEN-LAST:event_openRegistrationMenuButtonActionPerformed

    private void AppendNewUserToFile(String fileName, JSONObject newUserObject) throws RegExc{
            JSONParser jsonParser = new JSONParser();
            JSONArray listOfUsersObjects = new JSONArray();
            File file = new File(fileName);
            JSONObject newUser = (JSONObject)newUserObject.get("User");
            String newUserUsername = (String)newUser.get("username");;
            ArrayList allPreviousUsersUsernames = new ArrayList<String>();

            if(file.exists())
                try(FileReader reader = new FileReader(file)){
                    Object obj = jsonParser.parse(reader);

                    listOfUsersObjects = (JSONArray) obj;

                    listOfUsersObjects.forEach( objFromList -> {
                        JSONObject userObject = (JSONObject) objFromList;
                        JSONObject user = (JSONObject)userObject.get("User");
                        String currentUsername = (String)user.get("username");
                        
                        allPreviousUsersUsernames.add(currentUsername);
                    } );
                }catch(Exception ex){
                    ex.printStackTrace();
                    return;
                }

            if(allPreviousUsersUsernames.contains(newUserUsername)){
                throw new RegExc("User with that username already exists!");
            }
            
            listOfUsersObjects.add(newUserObject);

            try(FileWriter fileToWrite = new FileWriter(file)){
                fileToWrite.write(listOfUsersObjects.toJSONString());
                fileToWrite.flush();
            }catch(Exception ex){
                ex.printStackTrace();
            }
    }
    
    private void saveRegistrationDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRegistrationDataButtonActionPerformed
        try{
            String firstName = reg_firstName_textField.getText();
            if(firstName.equals("")) throw new RegExc("Write your first name!");
            String secondName = reg_secondName_textField.getText();
            if(secondName.equals("")) throw new RegExc("Write your second name!");
            String username = reg_username_textField.getText();
            if(username.equals("")) throw new RegExc("Write your username!");
            String password = reg_password_textField.getText();
            if(password.equals("")) throw new RegExc("Write you password!");
            String oneMorePassword = reg_passwordOneMore_textField.getText();
            if(!password.equals(oneMorePassword)) throw new RegExc("passwords didn't match");

            JSONObject userInfo = new JSONObject();
            userInfo.put("firstName", firstName);
            userInfo.put("secondName", secondName);
            userInfo.put("username", username);
            userInfo.put("password", password);

            JSONObject user = new JSONObject();
            user.put("User", userInfo);

            AppendNewUserToFile("Users.json", user);
        }catch(RegExc ex){
            reg_info_label.setForeground(Color.red);
            reg_info_label.setText(ex.getMessage());
            return;
        }
        reg_info_label.setForeground(new Color(15, 66, 22));
        reg_info_label.setText("Reģistrēšana ir veiksmīgi pabeigta!");
        
    }//GEN-LAST:event_saveRegistrationDataButtonActionPerformed

    private void enterProgrammButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterProgrammButtonActionPerformed
        String username = main_username.getText();
        String password = main_password.getText();
        
        JSONObject user = findUser("Users.json", username);
        
        if(user == null){
            main_info_label.setForeground(Color.red);
            main_info_label.setText("User with this username wasn't found!");
            return;
        }
        
        String userPassword = (String)user.get("password");
        if(!userPassword.equals(password)){
            main_info_label.setForeground(Color.red);
            main_info_label.setText("Password is incorrect!");
            return;
        }
        
        EnterProgramm(user);
    }//GEN-LAST:event_enterProgrammButtonActionPerformed

    private void EnterProgramm(JSONObject user){
        main_info_label.setForeground(new Color(15, 66, 22));
        main_info_label.setText("Entered!");
        
        myUser = new User(user);
        
        chatStartingWindow.setVisible(true);
        setVisible(false);
    }
    
    private void BeHostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeHostButtonActionPerformed
        new Thread(new Runnable(){
            @Override
            public void run() {
                try{
                    ServerSocket serverSocket = new ServerSocket(49751);
                    Server server = new Server(serverSocket, serverOutputArea);
                    server.startServer();
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
        }).start();

        System.out.println("Server started");
        serverIsWorkingWindow.setVisible(true);
        BeClientButton.doClick();

        chatStartingWindow.setVisible(false);
    }//GEN-LAST:event_BeHostButtonActionPerformed

    private void BeClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeClientButtonActionPerformed
        chatWindow.setVisible(true);
        chatStartingWindow.setVisible(false);
        
        try{
                System.out.println("Client starting...");

                //Socket socket = new Socket("192.168.12.1", 49751);
                Socket socket = new Socket(InetAddress.getLocalHost().getHostAddress(), 49751);
                client = new Client(socket, myUser.login, chatArea, userMessageField);
                client.listenForMessage();
                isClientConnnected = true;
                
                jPanel5.setBorder(BorderFactory.createTitledBorder(myUser.login));
                
                SimpleAttributeSet attributeSet = TextPresets.getOrangeItalic();
                int position = chatArea.getDocument().getLength();
                chatArea.getDocument().insertString(position, "Connected to server." + "\n", attributeSet);
                position = chatArea.getDocument().getLength();
                chatArea.getDocument().insertString(position, "Type !activities to open activities menu." + "\n", attributeSet);
                position = chatArea.getDocument().getLength();
                chatArea.getDocument().insertString(position, "--------------------" + "\n", attributeSet);
                
                userMessageField.setText("");
                
                System.out.println("Client started.");
            }catch(Exception ex){
                chatArea.setForeground(Color.red);
                chatArea.setText(chatArea.getText() + "Couldn't connect to server!!!" + "\n");
                ex.printStackTrace();
            }
    }//GEN-LAST:event_BeClientButtonActionPerformed

    private void userMessageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMessageFieldActionPerformed
        SendButton.doClick();
    }//GEN-LAST:event_userMessageFieldActionPerformed

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        String message = userMessageField.getText();
        if(message.startsWith("!")){
            String command = message.substring(1);
            if(command.equals("activities")){
                activityStartingMenu.setVisible(true);
                
                try{
                    int position = chatArea.getDocument().getLength();
                    chatArea.getDocument().insertString(position, "Opening menu!" + "\n", TextPresets.getGreenText());
                }catch(Exception ex){
                   ex.printStackTrace();
                }
            }
            else{
                try{
                    int position = chatArea.getDocument().getLength();
                    chatArea.getDocument().insertString(position, "Command \"" + command + "\" is unknown!" + "\n", TextPresets.getRedText());
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
        }
        else{
            System.out.println("Message sending...");
            client.sendMessage();
            System.out.println("Message Sended.");  
        }
        userMessageField.setText("");
    }//GEN-LAST:event_SendButtonActionPerformed

    private void chatWindowWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_chatWindowWindowClosing
        System.exit(0);
    }//GEN-LAST:event_chatWindowWindowClosing

    private void serverIsWorkingWindowWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_serverIsWorkingWindowWindowClosing
        System.exit(0);
    }//GEN-LAST:event_serverIsWorkingWindowWindowClosing

    private void chatStartingWindowWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_chatStartingWindowWindowClosing
        System.exit(0);
    }//GEN-LAST:event_chatStartingWindowWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void closeFirstQuizzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFirstQuizzButtonActionPerformed
        firstQuizzRightAnswers = 0;

        // First Question
        if(quizz1_firstQuestion_RadioButton1.isSelected()){
            firstQuizzRightAnswers++;
        }

        // Second Question
        if(quizz1_secondQuestion_TextField.getText().toLowerCase().equals("sports")){
            firstQuizzRightAnswers++;
        }

        // Third Question
        if(quizz2_thirdQuestion_List.isSelectedIndex(1)){
            firstQuizzRightAnswers++;
        }

        // Fourth Question
        int fourthQuestion = 0;
        if(quizz1_fourthQuestion_CheckBox1.isSelected()){
            fourthQuestion++;
        }
        if(quizz1_fourthQuestion_CheckBox2.isSelected()){
            fourthQuestion++;
        }
        if(quizz1_fourthQuestion_CheckBox3.isSelected()){
            fourthQuestion--;
        }
        if(quizz1_fourthQuestion_CheckBox4.isSelected()){
            fourthQuestion--;
        }
        if(fourthQuestion < 0){
            fourthQuestion = 0;
        }

        firstQuizzRightAnswers += fourthQuestion;

        // Fifth Question
        if(String.valueOf(quizz1_fifthQuestion_ComboBoxl.getSelectedItem()).equals("Direktors")){
            firstQuizzRightAnswers++;
        }

        System.out.println("Right answers: " + firstQuizzRightAnswers + " / 6");

        firstQuizz_RightAnswersNumber.setText(firstQuizzRightAnswers + " / 6");
        quizz1Maksimovs.setVisible(false);
    }//GEN-LAST:event_closeFirstQuizzButtonActionPerformed

    private void quizz1MaksimovsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_quizz1MaksimovsWindowClosed

    }//GEN-LAST:event_quizz1MaksimovsWindowClosed

    private void quizz1MaksimovsWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_quizz1MaksimovsWindowDeactivated
        
    }//GEN-LAST:event_quizz1MaksimovsWindowDeactivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        quizz1Maksimovs.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private JSONObject findUser(String fileName, String targetUsername){
        JSONParser jsonParser = new JSONParser();
        JSONArray listOfUsersObjects = new JSONArray();
        JSONObject foundedUser;
        File file = new File(fileName);

            if(file.exists())
                try(FileReader reader = new FileReader(file)){
                    Object obj = jsonParser.parse(reader);

                    listOfUsersObjects = (JSONArray) obj;

                    for(int i = 0; i < listOfUsersObjects.size(); i++){
                        JSONObject userObject = (JSONObject) listOfUsersObjects.get(i);
                        JSONObject user = (JSONObject)userObject.get("User");
                        String currentUsername = (String)user.get("username");
                        
                        if(currentUsername.equals(targetUsername)) return user;
                    }
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    class RegExc extends Exception{
        String message;
        
        public RegExc(String _message){
            message = _message;
        }
        
        public String getMessage(){
            return message;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BeClientButton;
    private javax.swing.JButton BeHostButton;
    private javax.swing.JPanel FifthQuestion;
    private javax.swing.JPanel FirstQuestion;
    private javax.swing.JPanel FourthQuestion;
    private javax.swing.JPanel SecondQuestion;
    private javax.swing.JButton SendButton;
    private javax.swing.JPanel ThirdQuestion;
    private javax.swing.JDialog activityStartingMenu;
    private javax.swing.JTextPane chatArea;
    private javax.swing.JDialog chatStartingWindow;
    private javax.swing.JDialog chatWindow;
    private javax.swing.JButton closeFirstQuizzButton;
    private javax.swing.JButton enterProgrammButton;
    private javax.swing.JLabel firstQuizz_RightAnswersNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel main_info_label;
    private javax.swing.JTextField main_password;
    private javax.swing.JTextField main_username;
    private javax.swing.JButton openRegistrationMenuButton;
    private javax.swing.JPanel questionsPanel;
    private javax.swing.JDialog quizz1Maksimovs;
    private javax.swing.JComboBox<String> quizz1_fifthQuestion_ComboBoxl;
    private javax.swing.JLabel quizz1_fifthQuestion_Label;
    private javax.swing.JLabel quizz1_firstQuestion_Label;
    private javax.swing.JRadioButton quizz1_firstQuestion_RadioButton1;
    private javax.swing.JRadioButton quizz1_firstQuestion_RadioButton2;
    private javax.swing.JRadioButton quizz1_firstQuestion_RadioButton3;
    private javax.swing.JCheckBox quizz1_fourthQuestion_CheckBox1;
    private javax.swing.JCheckBox quizz1_fourthQuestion_CheckBox2;
    private javax.swing.JCheckBox quizz1_fourthQuestion_CheckBox3;
    private javax.swing.JCheckBox quizz1_fourthQuestion_CheckBox4;
    private javax.swing.JLabel quizz1_fourthQuestion_Label;
    private javax.swing.JLabel quizz1_secondQuestion_Label;
    private javax.swing.JTextField quizz1_secondQuestion_TextField;
    private javax.swing.JLabel quizz1_thirdQuestion_Label;
    private javax.swing.JScrollPane quizz1_thirdQuestion_ScrollPane;
    private javax.swing.JList<String> quizz2_thirdQuestion_List;
    private javax.swing.JTextField reg_firstName_textField;
    private javax.swing.JLabel reg_info_label;
    private javax.swing.JTextField reg_passwordOneMore_textField;
    private javax.swing.JTextField reg_password_textField;
    private javax.swing.JTextField reg_secondName_textField;
    private javax.swing.JTextField reg_username_textField;
    private javax.swing.JDialog registrationWindow;
    private javax.swing.JButton saveRegistrationDataButton;
    private javax.swing.JDialog serverIsWorkingWindow;
    private javax.swing.JTextArea serverOutputArea;
    private javax.swing.JDialog testStartingWindow;
    private javax.swing.JTextField userMessageField;
    // End of variables declaration//GEN-END:variables
}
